server:
  port: 8089

spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver



  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: profile, email
            redirect-uri: ${GOOGLE_OAUTH_REDIRECT_URL}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  rabbitmq:
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    port: ${RABBITMQ_PORT}
    host: ${RABBITMQ_HOST}

  profiles:
    active: local

Paystack:
  apiKey: ${SECRET_KEY}
  uri: ${PAYSTACK_BASE_URI}

rabbitmq:
  exchange:
    name: ${RABBITMQ_EXCHANGE}
  queue:
    name: ${RABBITMQ_QUEUE}
  routing:
    key: ${RABBITMQ_ROUTING_KEY}

jwt:
  secret:
    key: ${JWT_SECRET_KEY}

Cloudinary:
  cloud-name: ${CLOUDINARY_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

google:
  credentials: ${GOOGLE_APPLICATION_CREDENTIALS}