server:
  port: 8089

spring:
  application:
    name: mentor-growth

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: profile, email
            redirect-uri: ${GOOGLE_OAUTH_REDIRECT_URL}


  datasource:
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

  rabbitmq:
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    port: ${RABBITMQ_PORT}
    host: ${RABBITMQ_HOST}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

Paystack:
  apiKey: ${PAYSTACK_SECRET}
  uri: ${PAYSTACK_BASE_URI}

jwt:
  secret:
    key: ${JWT_SECRET_KEY}

Cloudinary:
  cloud-name: ${CLOUDINARY_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

rabbitmq:
  exchange:
    name: mentorship_exchange
  queue:
    name: mentorship_queue
  routing:
    key: mentorship_routing_key

google:
  credentials:
    path: ${GOOGLE_APPLICATION_CREDENTIALS}
