server:
  port: 8089

spring:
  application:
    name: mentor-growth

  datasource:
    url: jdbc:postgresql://localhost:5432/mentor_growth
    username: postgres
    password: Emma007.
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

  rabbitmq:
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    port: 5672
    host: localhost

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

Paystack:
  apiKey: ${SECRET_KEY}
  uri: ${PAYSTACK_BASE_URI}

jwt:
  secret:
    key: ${JWT_SECRET_KEY}

Cloudinary:
  cloud-name: ${CLOUDINARY_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

rabbitmq:
  exchange:
    name: mentorship-exchange
  queue:
    name: mentorship_queue
  routing:
    key: mentorship_routing_key